service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  profile: default

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  products:
    handler: handler.getProductsList
    events:
     - httpApi:
         method: GET
         path: /products
         cors: true

  productsById:
    handler: handler.getProductsById
    events:
     - httpApi:
         method: GET
         path: /products/{id}
         cors: true
