service: import-service
frameworkVersion: '3'

useDotenv: true

provider:
  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  profile: default

  iamRoleStatements:
    - Effect: Allow
      Action: s3:ListBucket
      Resource:
      - arn:aws:s3:::${env:BUCKET_NAME}
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - arn:aws:s3:::${env:BUCKET_NAME}/*

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  importProducts:
    handler: handler.importProducts
    events:
     - httpApi:
         method: GET
         path: /import
         cors: true
