swagger: "2.0"
info:
  version: "1.0.0"
  title: "Product service"
  contact:
    email: "fruneen@gmail.com"
tags:
- name: "Products"
schemes:
- "https"
- "http"
paths:
  /products:
    get:
      tags:
       - "Products"
      summary: "Get all products"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
  /products/{id}:
    get:
      tags:
       - "Products"
      summary: "Get product by ID"
      description: "Returns a single prouduct"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of product to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
              $ref: "#/definitions/Product"
        "404":
          description: "Product not found"
definitions:
  Product:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      title:
        type: "string"
      description:
        type: "string"
      price:
        type: "number"
        format: "float"
      count:
        type: "number"
        format: "integer64"
